<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_entity_type_build().
 */
function po_cart_entity_type_build(array &$entity_types) {
  $entity_types['commerce_order_item']->setFormClass('po_ajax_add_to_cart', '\Drupal\po_cart\Form\AjaxAddToCartForm');
}

/**
 * Implements hook_theme().
 */
function po_cart_theme($existing, $type, $theme, $path) {
  $themeArray = [];

  $themeArray['po_add_cart_modal'] = [
    'variables' => [
      'product_variation' => NULL,
      'product_variation_entity' => NULL,
      'cart_url' => NULL,
    ],
  ];

  $themeArray['po_show_cart_modal'] = [
    'variables' => [
      'order_items' => NULL,
      'purchased_entity' => NULL,
      'messageList' => NULL,
      'cart_url' => NULL,
    ],
  ];

  return $themeArray;
}

/**
 * Implements hook_form_FORM_ID_alter() for 'entity_form_display_edit_form'.
 *
 * Hides irrelevant purchased_entity widgets on the dc_ajax_add_cart order item
 * form display.
 */
function po_cart_form_entity_form_display_edit_form_alter(array &$form, FormStateInterface $form_state) {
  /** @var \Drupal\Core\Entity\Display\EntityFormDisplayInterface $entity */
  $entity = $form_state->getFormObject()->getEntity();
  if ($form['#entity_type'] == 'commerce_order_item' && $entity->getMode() == 'po_ajax_add_to_cart') {
    $options = &$form['fields']['purchased_entity']['plugin']['type']['#options'];
    unset($options['commerce_entity_select']);
    unset($options['entity_reference_autocomplete_tags']);
    unset($options['entity_reference_autocomplete']);
    unset($options['inline_entity_form_complex']);
    unset($options['options_buttons']);
    unset($options['options_select']);
  }
}
