<?php

use Drupal\commerce_price\Price;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\BubbleableMetadata;
use Drupal\Core\Site\Settings;
use Drupal\cecc\Plugin\Commerce\CheckoutPane\PoShippingInformation;
use Drupal\cecc\Service\FormHelper;

/**
 * Implements hook_theme().
 */
function cecc_theme($existing, $type, $theme, $path) {
  $themeArray = [];

  $themeArray['catalog_admin_general'] = [
    'variables' => [],
  ];

  $themeArray['cec_limit_display'] = [
    'variables' => [
      'quantity_limit' => NULL,
    ],
  ];

  return $themeArray;
}

function cecc_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $formHelper = \Drupal::service('cecc.form_helper');
  $formHelper->alterForms($form, $form_state, $form_id);
}

/**
 * Implements hook_element_info_alter().
 */
function cecc_element_info_alter(array &$types) {
  if (isset($types['email'])) {
    // Add custom email validation for domains.
    $types['email']['#element_validate'][] = [FormHelper::class, 'validateEmail'];
  }
}

/**
 * Implements hook_entity_base_field_info_alter().
 */
function cecc_entity_base_field_info_alter(&$fields, EntityTypeInterface $entity_type) {
  if ($entity_type->id() == 'commerce_product_variation') {
    // Provide a default value callback for the price field.
    $fields['price']->setDefaultValueCallback('cecc_price_default_value');
  }
}

/**
 * Default value callback for the variation price field.
 *
 * @param \Drupal\Core\Entity\FieldableEntityInterface $entity
 *   The entity being created.
 * @param \Drupal\Core\Field\FieldDefinitionInterface $definition
 *   The field definition.
 * @return array
 */
function cecc_price_default_value(
  FieldableEntityInterface $entity,
  FieldDefinitionInterface $definition) {
  $bundle = $entity->bundle();

  if ($bundle == 'publication') {
    return [new Price('0', 'USD')];
  }
}

/**
 * Implements hook_commerce_checkout_pane_info_alter().
 */
function cecc_commerce_checkout_pane_info_alter(&$definitions) {
  if (isset($definitions['billing_information'])) {
    $definitions['billing_information']['class'] = PoShippingInformation::class;
    $definitions['billing_information']['provider'] = 'cecc';
  }
}

function cecc_commerce_inline_form_alter(
  array &$inline_form,
  FormStateInterface $form_state,
  array &$complete_form
) {
  /** @var \Drupal\commerce\Plugin\Commerce\InlineForm\InlineFormInterface $plugin */
  $plugin = $inline_form['#inline_form'];

  if ($plugin->getPluginId() == 'customer_profile') {
    if ($inline_form['#profile_scope'] == 'billing' && !isset($inline_form['rendered'])) {
      $inline_form['address']['widget'][0]['address']['#process'][] = ['Drupal\address\Element\Address', 'processAddress'];
      $inline_form['address']['widget'][0]['address']['#process'][] = 'cecc_address_fields';
    }
  }
}

function cecc_address_fields($element, $form_state) {
  $element['given_name']['#title'] = t('First Name');
  $element['family_name']['#title'] = t('Last Name');

  $element['address_line1']['#type'] = 'textarea';
  $element['address_line1']['#title'] = t('Street Address');
  $element['address_line1']['#maxlength'] = 255;
  $element['address_line1']['#attributes']['placeholder'] = t("Please enter your street address. Ex.\nOffice name (optional)\nBuilding name (optional)\nStreet address");

  $element['organization']['#attributes']['placeholder'] = t('Please enter your company or organization name.');
  $element['organization']['#description'] = t('Please enter your company or organization name.');
  $element['organization']['#title'] = t('Organization');

  $element['address_line2']['#description'] = t('Room or Suite Number. Ex. Room 104');
  $element['address_line2']['#attributes']['placeholder'] = t('Room or Suite Number. Ex. Room 104');
  $element['address_line2']['#maxlength'] = 20;

  $element['postal_code']['#title'] = t('Zip Code');
  $element['postal_code']['#maxlength'] = 20;

  return $element;
}

/**
 * Implements hook_mail_alter().
 */
function cecc_mail_alter(array &$message) {
  // Order receipt.
  if ($message['id'] === 'commerce_order_receipt') {
    /** @var \Drupal\commerce_order\Entity\OrderInterface $order */
    $order = $message['params']['order'];
    $config = \Drupal::config('cecc.settings');
    $siteConfig = \Drupal::config('system.site');

    $fromName = empty($config->get('email_from_name')) ? $siteConfig->get('name') :
    $config->get('email_from_name');

    $email = empty($config->get('email_from')) ? $siteConfig->get('mail') :
    $config->get('email_from');

    $message['from'] = $email;
    $message['headers']['Sender'] = $message['headers']['Return-Path'] = $message['from'];
    $message['headers']['From'] = t("@subject <@email>", [
      '@subject' => $fromName,
      '@email' => $email,
    ])->__toString();

    if (!empty($config->get('email_subject'))) {
      // Change the email subject.
      // @todo Remove this if/when it becomes configurable.
      //   https://www.drupal.org/project/commerce/issues/2924159
      $message['subject'] = t($config->get('email_subject'), [
        '@number' => $order->getOrderNumber(),
      ])->__toString();
    }
  }
}

function cecc_token_info() {
  $info = [];
  $info['tokens']['pattern']['environment'] = [
    'name' => t('Environment'),
    'description' => t('The current site environment'),
  ];

  return $info;
}

function cecc_tokens($type, $tokens, array $data, array $options, BubbleableMetadata $bubbleableMetadata) {
  $replacements = [];

  if ($type == 'pattern') {
    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'environment':
          $replacements[$original] = cecc_get_current_environment();
          break;
      }
    }
  }

  return $replacements;
}

function cecc_get_current_environment() {
  $environments = Settings::get('po_commerce_environments');
  /** @var \Symfony\Component\HttpFoundation\RequestStack $requestStack */
  $requestStack = \Drupal::service('request_stack');
  $request = $requestStack->getCurrentRequest();

  $host = $request->getSchemeAndHttpHost();

  if (empty($environments)) {
    return '';
  }

  return isset($environments[$host]) ? $environments[$host] . '-' : '';
}

/**
 * Implements hook_preprocess_HOOK().
 */
function cecc_preprocess_page_title(&$variables) {
  $routeName = \Drupal::routeMatch()->getRouteName();

  if ($routeName == 'commerce_cart.page') {
    $variables['title'] = t('Cart');
  }

  if ($routeName == 'commerce_checkout.form') {
    $variables['title'] = t('Order Information');
  }

}
